const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const output = process.env.QA_ARTIFACTS || path.resolve('test-artifacts');
fs.mkdirSync(output, {recursive:true});
(async () => {
  const browser = await chromium.launch({headless:true, ...(process.env.QA_CHROMIUM ? {executablePath:process.env.QA_CHROMIUM} : {})});
  const context = await browser.newContext({viewport:{width:1440,height:1100},timezoneId:'America/New_York'});
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  page.on('console', message => { if (['error','warning'].includes(message.type())) errors.push(message.text()); });
  await page.clock.install({time:new Date('2026-09-08T16:00:00Z')});
  await page.goto('http://127.0.0.1:8765');
  await page.locator('#today-completed').waitFor();
  assert.match(await page.locator('#today-completed').innerText(), /0.*\/ 5/s);
  assert.equal(await page.locator('.plan-item').count(), 5);
  await page.screenshot({path:path.join(output,'today-desktop.png'),fullPage:true});
  await page.locator('[data-check]').first().click();
  assert.match(await page.locator('#today-completed').innerText(), /1.*\/ 5/s);
  assert.equal(await page.locator('#week-total').innerText(), '1');
  await page.reload();
  assert.equal(await page.locator('[data-check]').first().getAttribute('aria-pressed'), 'true');
  await page.locator('[data-view="stats"]').click();
  assert.match(await page.locator('[data-overview="week"] strong').innerText(), /1/);
  assert.equal(await page.locator('.calendar-day.has-checkin').count(), 1);
  await page.locator('[data-date="2026-09-08"]').click();
  assert.match(await page.locator('#selected-day').innerText(), /坐姿推胸/);
  await page.locator('[data-view="today"]').click();
  await page.locator('[data-check]').first().click();
  assert.equal(await page.locator('#week-total').innerText(), '0');
  // Representative historical v2 data, confined to this isolated browser context.
  await page.evaluate(() => localStorage.setItem('fitguide.checkin.v2', JSON.stringify({plan:'ppl',day:'push',done:{ppl:{push:{'machine-chest-press':['2026-09-07','2026-09-08','2026-08-31','2026-01-01','2025-12-31'],'cable-chest-fly':['2026-09-08']},pull:{'face-pull':['2026-09-08']}},single:{chest:{'machine-chest-press':['2026-09-08']}}}})));
  await page.reload();
  await page.locator('[data-view="stats"]').click();
  assert.match(await page.locator('[data-overview="week"] strong').innerText(), /2/);
  assert.match(await page.locator('[data-overview="week"] .overview-caption').innerText(), /4 次/);
  assert.match(await page.locator('[data-overview="year"] strong').innerText(), /4/);
  await page.locator('[data-period="month"]').click();
  assert.equal(await page.locator('.calendar-day').count(), 30);
  assert.equal(await page.locator('.calendar-blank').count(), 1);
  await page.locator('#period-prev').click();
  assert.match(await page.locator('#period-title').innerText(), /8月/);
  assert.equal(await page.locator('.calendar-day').count(), 31);
  await page.locator('#period-current').click();
  assert.match(await page.locator('#period-title').innerText(), /9月/);
  assert.equal(await page.locator('#period-next').isDisabled(), true);
  await page.locator('[data-period="year"]').click();
  assert.equal(await page.locator('[data-month]').count(), 12);
  await page.locator('[data-month="7"]').click();
  assert.match(await page.locator('#period-title').innerText(), /8月/);
  await page.locator('[data-period="year"]').click();
  await page.locator('#period-prev').click();
  assert.match(await page.locator('#period-title').innerText(), /2025/);
  assert.match(await page.locator('#period-summary').innerText(), /1/);
  await page.locator('[data-period="month"]').click();
  await page.screenshot({path:path.join(output,'stats-desktop.png'),fullPage:true});
  for (const width of [320,390,768,1440]) {
    await page.setViewportSize({width,height:844});
    for (const view of ['today','stats','library']) {
      await page.locator(`[data-view="${view}"]`).click();
      const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth);
      assert.equal(overflow, false, `${width}px ${view} overflows`);
      if (width === 390) await page.screenshot({path:path.join(output,`${view}-mobile.png`),fullPage:true});
    }
  }
  await page.locator('[data-category="back"]').click();
  assert.equal(await page.locator('#result-count').innerText(), '5 个动作');
  await page.locator('.advanced-filters summary').click();
  await page.locator('#search').fill('不存在的动作');
  assert.equal(await page.locator('#empty').isVisible(), true);
  await page.locator('#empty-reset').click();
  assert.equal(await page.locator('#result-count').innerText(), '24 个动作');
  await page.locator('[data-view="today"]').click();
  await page.locator('.plan-detail').first().click();
  assert.equal(await page.locator('#detail').isVisible(), true);
  assert.match(await page.locator('#detail-title').innerText(), /坐姿推胸/);
  assert.equal(await page.locator('#detail video').count(), 1);
  await page.locator('#close-detail').click();
  assert.equal(await page.locator('#detail').isVisible(), false);
  await page.locator('#plan-reset').click();
  const saved = await page.evaluate(() => JSON.parse(localStorage.getItem('fitguide.checkin.v2')));
  assert.equal(saved.done.ppl.push['machine-chest-press'].includes('2026-09-08'), false);
  assert.equal(saved.done.ppl.push['machine-chest-press'].includes('2026-09-07'), true);
  assert.equal(saved.done.ppl.pull['face-pull'].includes('2026-09-08'), true);
  await page.clock.runFor(12 * 60 * 60 * 1000);
  assert.match(await page.locator('#today-date').innerText(), /9月9日/);
  assert.match(await page.locator('#today-completed').innerText(), /0.*\/ 5/s);
  assert.deepEqual(errors, []);
  await browser.close();
  console.log('PASS: v2 persistence, check/undo/reset, date drilldown, week/month/year navigation, cross-year history, midnight refresh, 320/390/768/1440 layouts, filters and video dialog. No browser errors/warnings.');
})().catch(error => { console.error(error); process.exit(1); });
